# Triggers a release build on JitPack

name: jitpack-build

on:
  push:
    tags: [ '*' ]

jobs:
  jitpack:
    runs-on: ubuntu-latest
    steps:
      - name: Request latest release build from JitPack
        run: |
          # timeout in 30 seconds to avoid waiting for build
          echo % curl -s -m 30 https://jitpack.io/com/github/$GITHUB_REPOSITORY/$GITHUB_REF_NAME/maven-metadata.xml
          curl -s -m 30 https://jitpack.io/com/github/$GITHUB_REPOSITORY/$GITHUB_REF_NAME/maven-metadata.xml || true